<?php

//class Robot{
//    public function greet(){
//        return "Hello \n";
//    }
//}
//class Android extends Robot{
//    public function greet()
//    {
//        return "Hi \n"; // TODO: Change the autogenerated stub
//    }
//
//}
//$robot = new Robot();
//echo $robot->greet();
//$android = new Android();
//echo $android->greet();
class Robot{
    public function greet(){
        return "Hello \n";
    }
}
class Android extends Robot{
    public function greet()
    {
        $greeting = $this->greet();
        return $greeting ." From Android \n"; // TODO: Change the autogenerated stub
    }

}

$android = new Android();
$android->greet();